# Generated by Django 4.1.4 on 2023-01-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_person_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='des1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='person',
            name='des2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='person',
            name='des3',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
