# Generated by Django 4.1.4 on 2023-01-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_person_des1_alter_person_des2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
