# Generated by Django 4.1.4 on 2023-01-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_uname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uname',
        ),
    ]
